#############################################################################
# Makefile for building: HeadTiltingDetection
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sat Mar 26 20:57:57 2016
# Project:  HeadTiltingDetection.pro
# Template: app
# Command: /home/valerio/anaconda2/bin/qmake -config release -o Makefile HeadTiltingDetection.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../anaconda2/mkspecs/linux-g++ -I. -I../../anaconda2/include/QtCore -I../../anaconda2/include/QtGui -I../../anaconda2/include -I. -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/valerio/anaconda2/lib
LIBS          = $(SUBLIBS)  -L/home/valerio/anaconda2/lib `pkg-config opencv --cflags --libs` -lQtGui -L/home/valerio/anaconda2/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/valerio/anaconda2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o \
		qrc_resources.o
DIST          = ../../anaconda2/mkspecs/common/unix.conf \
		../../anaconda2/mkspecs/common/linux.conf \
		../../anaconda2/mkspecs/common/gcc-base.conf \
		../../anaconda2/mkspecs/common/gcc-base-unix.conf \
		../../anaconda2/mkspecs/common/g++-base.conf \
		../../anaconda2/mkspecs/common/g++-unix.conf \
		../../anaconda2/mkspecs/qconfig.pri \
		../../anaconda2/mkspecs/modules/qt_webkit_version.pri \
		../../anaconda2/mkspecs/features/qt_functions.prf \
		../../anaconda2/mkspecs/features/qt_config.prf \
		../../anaconda2/mkspecs/features/exclusive_builds.prf \
		../../anaconda2/mkspecs/features/default_pre.prf \
		../../anaconda2/mkspecs/features/release.prf \
		../../anaconda2/mkspecs/features/default_post.prf \
		../../anaconda2/mkspecs/features/shared.prf \
		../../anaconda2/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../anaconda2/mkspecs/features/warn_on.prf \
		../../anaconda2/mkspecs/features/qt.prf \
		../../anaconda2/mkspecs/features/unix/thread.prf \
		../../anaconda2/mkspecs/features/moc.prf \
		../../anaconda2/mkspecs/features/resources.prf \
		../../anaconda2/mkspecs/features/uic.prf \
		../../anaconda2/mkspecs/features/yacc.prf \
		../../anaconda2/mkspecs/features/lex.prf \
		../../anaconda2/mkspecs/features/include_source_dir.prf \
		HeadTiltingDetection.pro
QMAKE_TARGET  = HeadTiltingDetection
DESTDIR       = 
TARGET        = HeadTiltingDetection

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HeadTiltingDetection.pro  ../../anaconda2/mkspecs/linux-g++/qmake.conf ../../anaconda2/mkspecs/common/unix.conf \
		../../anaconda2/mkspecs/common/linux.conf \
		../../anaconda2/mkspecs/common/gcc-base.conf \
		../../anaconda2/mkspecs/common/gcc-base-unix.conf \
		../../anaconda2/mkspecs/common/g++-base.conf \
		../../anaconda2/mkspecs/common/g++-unix.conf \
		../../anaconda2/mkspecs/qconfig.pri \
		../../anaconda2/mkspecs/modules/qt_webkit_version.pri \
		../../anaconda2/mkspecs/features/qt_functions.prf \
		../../anaconda2/mkspecs/features/qt_config.prf \
		../../anaconda2/mkspecs/features/exclusive_builds.prf \
		../../anaconda2/mkspecs/features/default_pre.prf \
		../../anaconda2/mkspecs/features/release.prf \
		../../anaconda2/mkspecs/features/default_post.prf \
		../../anaconda2/mkspecs/features/shared.prf \
		../../anaconda2/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../anaconda2/mkspecs/features/warn_on.prf \
		../../anaconda2/mkspecs/features/qt.prf \
		../../anaconda2/mkspecs/features/unix/thread.prf \
		../../anaconda2/mkspecs/features/moc.prf \
		../../anaconda2/mkspecs/features/resources.prf \
		../../anaconda2/mkspecs/features/uic.prf \
		../../anaconda2/mkspecs/features/yacc.prf \
		../../anaconda2/mkspecs/features/lex.prf \
		../../anaconda2/mkspecs/features/include_source_dir.prf \
		/home/valerio/anaconda2/lib/libQtGui.prl \
		/home/valerio/anaconda2/lib/libQtCore.prl
	$(QMAKE) -config release -o Makefile HeadTiltingDetection.pro
../../anaconda2/mkspecs/common/unix.conf:
../../anaconda2/mkspecs/common/linux.conf:
../../anaconda2/mkspecs/common/gcc-base.conf:
../../anaconda2/mkspecs/common/gcc-base-unix.conf:
../../anaconda2/mkspecs/common/g++-base.conf:
../../anaconda2/mkspecs/common/g++-unix.conf:
../../anaconda2/mkspecs/qconfig.pri:
../../anaconda2/mkspecs/modules/qt_webkit_version.pri:
../../anaconda2/mkspecs/features/qt_functions.prf:
../../anaconda2/mkspecs/features/qt_config.prf:
../../anaconda2/mkspecs/features/exclusive_builds.prf:
../../anaconda2/mkspecs/features/default_pre.prf:
../../anaconda2/mkspecs/features/release.prf:
../../anaconda2/mkspecs/features/default_post.prf:
../../anaconda2/mkspecs/features/shared.prf:
../../anaconda2/mkspecs/features/unix/gdb_dwarf_index.prf:
../../anaconda2/mkspecs/features/warn_on.prf:
../../anaconda2/mkspecs/features/qt.prf:
../../anaconda2/mkspecs/features/unix/thread.prf:
../../anaconda2/mkspecs/features/moc.prf:
../../anaconda2/mkspecs/features/resources.prf:
../../anaconda2/mkspecs/features/uic.prf:
../../anaconda2/mkspecs/features/yacc.prf:
../../anaconda2/mkspecs/features/lex.prf:
../../anaconda2/mkspecs/features/include_source_dir.prf:
/home/valerio/anaconda2/lib/libQtGui.prl:
/home/valerio/anaconda2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -config release -o Makefile HeadTiltingDetection.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/HeadTiltingDetection1.0.0 || $(MKDIR) .tmp/HeadTiltingDetection1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/HeadTiltingDetection1.0.0/ && $(COPY_FILE) --parents mainwindow.h HelpingFun.h HelpingFun.h .tmp/HeadTiltingDetection1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/HeadTiltingDetection1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/HeadTiltingDetection1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/HeadTiltingDetection1.0.0/ && (cd `dirname .tmp/HeadTiltingDetection1.0.0` && $(TAR) HeadTiltingDetection1.0.0.tar HeadTiltingDetection1.0.0 && $(COMPRESS) HeadTiltingDetection1.0.0.tar) && $(MOVE) `dirname .tmp/HeadTiltingDetection1.0.0`/HeadTiltingDetection1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/HeadTiltingDetection1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/home/valerio/anaconda2/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		moveLeft.wav \
		flipVert.png \
		flipRight.png \
		flipHorz.png \
		moveRight.wav \
		flipLeft.png
	/home/valerio/anaconda2/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/valerio/anaconda2/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		HelpingFun.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

